[tool.poetry]
name = "gino-admin"
version = "0.2.0-alpha3"
description = "Admin Panel for PostgreSQL DB with Gino ORM"
authors = ["xnuinside <xnuinside@gmail.com>"]
license = "MIT"
readme = "docs/README.rst"
homepage = "https://github.com/xnuinside/gino-admin"
repository = "https://github.com/xnuinside/gino-admin"

[tool.poetry.dependencies]
python = "^3.7"
sanic-auth = "^0.2.0"
Sanic = "^19.12.2"
Sanic-Jinja2 = "^0.7.5"
passlib = "^1.7.2"
aiofiles = "^0.5.0"
expiring_dict = "^1.1.0"
PyYAML = "^5.3.1"
gino = "^1.0.0"
gino-sanic = "^0.1.0"
SQLAlchemy-Utils = "0.36.5"
click = "^7.1.2"
sanic-jwt = "^1.4.1"
requests_html = "^0.10.0"
pydantic = "^1.5.1"

[tool.poetry.dev-dependencies]
pre-commit = "^2.3.0"
flake8 = "^3.7.9"
pytest-docker-compose = "^3.1.2"
pytest = "^5.4.2"
sphinx = "^3.0.3"

[tool.poetry.scripts]
gino-admin = 'gino_admin.cli:cli'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
